# Generated by Django 5.2.1 on 2025-05-11 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_quiz_category_quiz_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='quizzes.quiz')),
            ],
        ),
    ]
